from typing import TYPE_CHECKING

import matplotlib.patches as mpatches
import matplotlib.pyplot as plt
from pygsp import filters

if TYPE_CHECKING:
    from pygsp.graphs import Graph


def plot_itersine(G_Sensor: "Graph", G_ER: "Graph", Nf: int = 7) -> None:
    """Plots the Itersine filter bank for two graphs side by side,
    and the Laplacian eigenvalues on the x-axis.

    Args:
        G_Sensor: Sensor graph
        G_ER: Erdős-Rényi graph.
        Nf: Number of filters in the filter bank.
    """
    fig, axes = plt.subplots(1, 2, figsize=(10, 4))

    # Signal Graph
    G_Sensor.estimate_lmax()
    g_Sensor = filters.Itersine(G_Sensor, Nf=Nf)
    g_Sensor.plot(ax=axes[0])

    axes[0].set_title("Signal Graph")

    # Hide legend if auto-generated by the plot method
    if axes[0].get_legend() is not None:
        axes[0].get_legend().remove()

    # ER Graph
    G_ER.estimate_lmax()
    g_er = filters.Itersine(G_ER, Nf=Nf)
    g_er.plot(ax=axes[1])

    axes[1].set_title("Erdős-Rényi Graph")

    # Hide legend if auto-generated by the plot method
    if axes[1].get_legend() is not None:
        axes[1].get_legend().remove()

    # Extract labels and colors from the first axis to build the new legend
    handles, labels = axes[0].get_legend_handles_labels()

    # Create square patches for a compact legend
    square_handles = [
        mpatches.Patch(color=h.get_color(), label=label)
        for h, label in zip(handles, labels)
    ]

    fig.legend(
        handles=square_handles,
        labels=labels,
        loc="lower center",
        bbox_to_anchor=(0.5, 0),
        ncol=len(labels),
        handlelength=1.0,  # Compacts the square width
        handleheight=1.0,  # Compacts the square height
    )

    plt.tight_layout(rect=[0, 0.1, 1, 1])
    plt.savefig("./out/itersine_comparison.pdf", bbox_inches="tight")
    plt.close(fig)
