import numpy as np
import numpy.linalg as LA

# Requires latex installed
import scienceplots  # noqa: F401
from pygsp import graphs

from afgl.plot.ex1 import plot_error_comparison, plot_graphs
from afgl.util.g_function import (
    compute_g_itersine,
    compute_g_M,
    filter_signal_with_fourier,
)
from afgl.util.lanczos import lanczos


def run_comparison_1_for_graph(
    G, s: np.ndarray, M_MAX: int
) -> tuple[np.ndarray, np.ndarray]:
    """Compares the error with error generated by Lanczos.

    Args:
        G: Graph
        s: Signal vector

    Returns:
        [lanczos_err, true_err]: Vectors of errors norm(g_{M+3} - g_M) and norm(e_M)
        as defined in [1]
    """
    G.compute_laplacian("combinatorial")
    L = G.L

    j = 3
    g = compute_g_itersine(G)

    (
        V,
        T,
        _,
    ) = lanczos(L, s, M_MAX + j)

    lanczos_err = np.zeros(M_MAX)
    true_err = np.zeros(M_MAX)

    GLs = filter_signal_with_fourier(G, s, g)

    for M in range(1, M_MAX + 1):
        g_M = compute_g_M(V[:, :M], T[:M, :M], s, g)
        g_Mj = compute_g_M(V[:, : M + j], T[: M + j, : M + j], s, g)

        lanczos_err[M - 1] = LA.norm(g_Mj - g_M)
        true_err[M - 1] = LA.norm(GLs - g_M)

    return lanczos_err, true_err


def run_plot_graphs(G_ER, G_Sensor, s, N, p) -> None:
    signal_ER = filter_signal_with_fourier(G_ER, s)
    signal_S = filter_signal_with_fourier(G_Sensor, s)

    plot_graphs(G_ER, G_Sensor, s, signal_ER, signal_S, N, p)


def run() -> None:
    """Ripete il test corrispondente ad Example 1 dell'articolo limitandosi al
    metodo di Lanczos (no Chebyshev) e utilizzando come funzione g(t) = sin(0.5π
    cos(πt)2) * chi_{[-0.5, 0.5]}.
    """
    N = 500
    M = 200
    p = 0.04

    s = np.random.rand(N).astype(float)
    # Normalize s as in request
    s /= LA.norm(s)

    G_ER = graphs.ErdosRenyi(N, p)
    G_S = graphs.Sensor(N)

    l_err_ER, t_err_ER = run_comparison_1_for_graph(G_ER, s, M)
    l_err_S, t_err_S = run_comparison_1_for_graph(G_S, s, M)

    plot_error_comparison(l_err_ER, t_err_ER, l_err_S, t_err_S)
    # run_plot_graphs(G_ER, G_S, s, N, p)
