import numpy as np
import numpy.linalg as LA

# Requires latex installed
import scienceplots  # noqa: F401
import scipy
from pygsp import graphs

from afgl.util.ex1_plot import plot_error_comparison, plot_graphs
from afgl.util.lanczos import lanczos
from afgl.util.T_tridiag import T_tridiag

"""
TODO: Fix this misbehaviour
Steps tried: 
- translating g to max eigenvalue (see gemini conversation)
- Leaving g untouched (sure it's not ok) but normalizing L with L = L/lmax: it
  gives smooth curve but it goes too low
- Translating np.sin(1 / 2 * np.pi * (np.cos(np.pi * t - 1/2) ** 2)) and
  normalizing L as above, it gives close errors but curves are not smooth.
- Dividing L by l_max*2

"""


def g_extended(t: np.ndarray) -> np.ndarray:
    return np.sin(1 / 2 * np.pi * (np.cos(np.pi * t) ** 2))


"""
Evaluates the function sin(0.5*pi*cos(pi*t)^2)chi_[-1/2,1/2] where chi_I is the
characteristic function of I, as defined in example 1 (see [1]).
"""


def g(T: np.ndarray) -> np.ndarray:
    if scipy.sparse.issparse(T):
        # Operator & not supporting sparse matrix
        T = T.toarray()
    Chi = ((T >= -1 / 2) & (T <= 1 / 2)).astype(int)
    # Apply g_extended where Chi is True, else output 0
    return np.where(Chi, g_extended(T), 0)


def compute_g_M(
    V: np.ndarray, alp: np.ndarray, beta: np.ndarray, s: np.ndarray
) -> np.ndarray:
    """
    Computes the approximation g_M (see [1]) using Lanczos
    """
    M = len(alp)
    e_1 = np.zeros(M)
    e_1[0] = 1
    T = T_tridiag(alp, beta)

    eigvals, eigvecs = LA.eigh(T)
    g_T = eigvecs @ np.diag(g(eigvals)) @ eigvecs.T

    y = LA.norm(s) * (g_T @ e_1)
    return V @ y


def filter_signal_with_fourier(G, s: np.ndarray) -> np.ndarray:
    """Returns evaluation Ug(Λ)U*s, which is the filtered signal using the
    fourier basis.
    """
    G.compute_fourier_basis()
    U = G.U
    return (U @ np.diag(g(G.e)) @ U.T) @ s


def run_comparison_1_for_graph(
    G, s: np.ndarray, M_MAX: int
) -> tuple[np.ndarray, np.ndarray]:
    """Compares the error with error generated by Lanczos.

    Args:
        G: Graph
        s: Signal vector

    Returns:
        [lanczos_err, true_err]: Vectors of errors norm(g_{M+3} - g_M) and norm(e_M)
        as defined in [1]
    """
    G.compute_laplacian("combinatorial")
    G.estimate_lmax()
    G.L = G.L / (2 * G.lmax)
    L = G.L

    j = 3
    (
        V,
        alp,
        beta,
        _,
    ) = lanczos(L, s, M_MAX + j)

    lanczos_err = np.zeros(M_MAX)
    true_err = np.zeros(M_MAX)

    GLs = filter_signal_with_fourier(G, s)

    for M in range(1, M_MAX + 1):
        g_M = compute_g_M(V[:, :M], alp[:M], beta[: M - 1], s)
        g_Mj = compute_g_M(V[:, : M + j], alp[: M + j], beta[: M + j - 1], s)

        lanczos_err[M - 1] = LA.norm(g_Mj - g_M)
        true_err[M - 1] = LA.norm(GLs - g_M)

    return lanczos_err, true_err


def run_plot_graphs(G_ER, G_Sensor, s, N, p) -> None:
    signal_ER = filter_signal_with_fourier(G_ER, s)
    signal_S = filter_signal_with_fourier(G_Sensor, s)

    plot_graphs(G_ER, G_Sensor, s, signal_ER, signal_S, N, p)


def run() -> None:
    """Ripete il test corrispondente ad Example 1 dell'articolo limitandosi al
    metodo di Lanczos (no Chebyshev) e utilizzando come funzione g(t) = sin(0.5π
    cos(πt)2) * chi_{[-0.5, 0.5]}.
    """
    N = 500
    M = 200
    p = 0.04

    s = np.random.rand(N).astype(float)
    # Normalize s as in request
    s /= LA.norm(s)

    G_ER = graphs.ErdosRenyi(N, p)
    G_S = graphs.Sensor(N)

    l_err_ER, t_err_ER = run_comparison_1_for_graph(G_ER, s, M)
    l_err_S, t_err_S = run_comparison_1_for_graph(G_S, s, M)

    plot_error_comparison(l_err_ER, t_err_ER, l_err_S, t_err_S)
    # run_plot_graphs(G_ER, G_S, s, N, p)
